---
# Install RedHat Variant Version of bitflux.
- name: Add Bitflux Repository to yum/dnf
  ansible.builtin.template:
    src: bitflux.repo.j2
    dest: /etc/yum.repos.d/bitflux.repo

- name: Install main bitflux collector package
  ansible.builtin.dnf:
    name: bitfluxcollector
    state: present

- name: Enable Bitflux Kernel Updates over standard kernel Updates (optional - enables proactive memory management)
  ansible.builtin.lineinfile:
    path: /etc/yum.repos.d/*-BaseOS.repo
    regexp: '^exclude='
    line: "exclude=kernel kernel-*"
  when: bitflux_enableKernel == true

- name: Replace Kernel with Bitflux Kernel (optional - enables proactive memory management)
  ansible.builtin.dnf:
    name: kernel
    enablerepo: bitflux
    state: present
  when: bitflux_enableKernel == true

- name: Enable swaphints module on boot. (optional - enables proactive memory management)
  copy:
    dest: "/etc/modules-load.d/swaphints.conf"
    content: 'swaphints'
    mode: '0644'
    owner: root
    group: root
  when: bitflux_enableKernel == true